[2024-10-13T23:14:33.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T23:14:33.672+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_workflow_jhayr.preprocess_data manual__2024-10-13T23:13:18.646006+00:00 [queued]>
[2024-10-13T23:14:33.689+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_workflow_jhayr.preprocess_data manual__2024-10-13T23:13:18.646006+00:00 [queued]>
[2024-10-13T23:14:33.692+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-13T23:14:33.715+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-10-13 23:13:18.646006+00:00
[2024-10-13T23:14:33.737+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-13T23:14:33.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_workflow_jhayr', 'preprocess_data', 'manual__2024-10-13T23:13:18.646006+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp85ntlotm']
[2024-10-13T23:14:33.742+0000] {standard_task_runner.py:72} INFO - Started process 319 to run task
[2024-10-13T23:14:33.743+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask preprocess_data
[2024-10-13T23:14:33.840+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_workflow_jhayr.preprocess_data manual__2024-10-13T23:13:18.646006+00:00 [running]> on host d8275d2c7247
[2024-10-13T23:14:33.997+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_workflow_jhayr' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T23:13:18.646006+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T23:13:18.646006+00:00'
[2024-10-13T23:14:34.000+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T23:14:34.001+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T23:14:34.002+0000] {logging_mixin.py:190} INFO - Current task name:preprocess_data state:running start_date:2024-10-13 23:14:33.673335+00:00
[2024-10-13T23:14:34.003+0000] {logging_mixin.py:190} INFO - Dag name:ml_workflow_jhayr and current dag run status:running
[2024-10-13T23:14:34.003+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T23:14:34.348+0000] {python.py:240} INFO - Done. Returned value was: (       person_age  person_income  ...  loan_grade_G  cb_person_default_on_file_Y
0        1.627294      -0.924586  ...             0                            0
1       -0.939274      -0.240147  ...             0                            0
2        0.258458      -1.126658  ...             0                            0
3        0.429562       0.216146  ...             0                            0
4       -0.939274      -0.109777  ...             0                            0
...           ...            ...  ...           ...                          ...
58640    1.113981       1.845763  ...             0                            1
58641    0.087353      -1.126658  ...             0                            0
58642   -0.768170      -0.631255  ...             0                            0
58643   -0.939274      -1.087548  ...             0                            0
58644    0.600667       0.379108  ...             0                            0

[58481 rows x 22 columns], 0        0
1        0
2        0
3        0
4        0
        ..
58640    0
58641    1
58642    1
58643    0
58644    0
Name: loan_status, Length: 58481, dtype: int64, 0            0
1            1
2            2
3            3
4            4
         ...  
58640    58640
58641    58641
58642    58642
58643    58643
58644    58644
Name: id, Length: 58481, dtype: int64)
[2024-10-13T23:14:34.552+0000] {xcom.py:690} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-10-13T23:14:34.556+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 151, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 128, in serialize
    return [serialize(d, depth + 1) for d in o]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 103, in encode
    o = self.default(o)
        ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-10-13T23:14:34.577+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-13T23:14:34.579+0000] {logging_mixin.py:190} INFO - Task start:2024-10-13 23:14:33.673335+00:00 end:2024-10-13 23:14:34.575866+00:00 duration:0.902531
[2024-10-13T23:14:34.580+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): preprocess_data> dag:<DAG: ml_workflow_jhayr> dagrun:<DagRun ml_workflow_jhayr @ 2024-10-13 23:13:18.646006+00:00: manual__2024-10-13T23:13:18.646006+00:00, state:running, queued_at: 2024-10-13 23:13:18.713418+00:00. externally triggered: True>
[2024-10-13T23:14:34.581+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type tuple is not JSON serializable
[2024-10-13T23:14:34.582+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_workflow_jhayr, task_id=preprocess_data, run_id=manual__2024-10-13T23:13:18.646006+00:00, execution_date=20241013T231318, start_date=20241013T231433, end_date=20241013T231434
[2024-10-13T23:14:34.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T23:14:34.613+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task preprocess_data (Object of type tuple is not JSON serializable; 319)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 151, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 128, in serialize
    return [serialize(d, depth + 1) for d in o]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 103, in encode
    o = self.default(o)
        ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-10-13T23:14:34.684+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T23:14:34.745+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T23:14:34.757+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
